"""Assemble the per-measurement gallery: frame, spectrum, link, in one table.

Pulls together the three artefacts produced by ``stream_index.py``,
``frames_from_stream.py`` and ``plot_spectra.py`` so that a reader can go from
a number, to the picture of the deck at the instant that number was taken, to
the point in the livestream, without leaving the page.

``SCENE`` is the one hand-entered part: a note of what is visible in each
frame. It is a visual reading of the committed images, not something measured,
so it is kept here in the open rather than buried in a results file -- anyone
can click the link and disagree.
"""

from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = "https://github.com/vertical-cloud-lab/byu-vcl/blob/{sha}/wireless-color-sensor/ot2/{path}?raw=true"

RUN_TITLES = [
    ("xscan-run-2026-09-09.json", "Run 1 — slot 8, read z 120", "01:11–01:15 UTC"),
    ("xscan-slot7-2026-09-09.json", "Run 2 — slot 7, read z 125", "01:27–01:31 UTC"),
    ("xscan-slot7-z120-2026-09-09.json", "Run 3 — slot 7, read z 120 (control)", "01:31–01:34 UTC"),
    ("xscan-slot7-z128-2026-09-09.json", "Run 4 — slot 7, read z 128", "01:41–01:45 UTC"),
    ("xscan-slot7-paint-2026-09-09.json", "Run 5 — slot 7, z 128, vials (3 positions)", "01:51–01:55 UTC"),
    ("xscan-slot7-sweep-2026-09-09.json", "Run 6 — slot 7, z 128, vials (9-position sweep)", "01:56–02:01 UTC"),
    ("xscan-slot7-z129-press90-2026-09-09.json", "Run 7 — slot 7, z 129, press 90.0", "02:20–02:24 UTC"),
]

# What is actually visible in each committed frame. "clear" means the deck and
# nobody else; anything else names what is in shot.
SCENE = {
    "run-2026-09-09-pos1-dx-30": "hand holding a yellow vial beside the module; head in shot",
    "run-2026-09-09-pos2-dxp0": "hand holding a yellow vial beside the module; head in shot",
    "run-2026-09-09-pos3-dxp30": "clear, deck empty",
    "slot7-2026-09-09-pos1-dx-30": "hand placing a red vial beside the module; head in shot",
    "slot7-2026-09-09-pos2-dxp0": "hand on the red vial; head in shot",
    "slot7-2026-09-09-pos3-dxp30": "red vial standing on the deck; arm across the top of the frame",
    "slot7-z120-2026-09-09-pos1-dx-30": "clear, deck empty",
    "slot7-z120-2026-09-09-pos2-dxp0": "clear, deck empty",
    "slot7-z120-2026-09-09-pos3-dxp30": "clear, deck empty",
    "slot7-z128-2026-09-09-pos1-dx-30": "person fills the right half of the frame, placing the yellow vial",
    "slot7-z128-2026-09-09-pos2-dxp0": "arm reaching across the deck, placing the red vial",
    "slot7-z128-2026-09-09-pos3-dxp30": "all three vials down, nobody in shot",
    "slot7-paint-2026-09-09-pos1-dx-30": "three vials, clear",
    "slot7-paint-2026-09-09-pos2-dxp0": "hand and a dark object at the right edge",
    "slot7-paint-2026-09-09-pos3-dxp30": "three vials, clear",
    "slot7-sweep-2026-09-09-pos1-dx-60": "three vials, clear",
    "slot7-sweep-2026-09-09-pos2-dx-50": "three vials, clear",
    "slot7-sweep-2026-09-09-pos3-dx-40": "three vials, clear",
    "slot7-sweep-2026-09-09-pos4-dx-30": "three vials, clear",
    "slot7-sweep-2026-09-09-pos5-dx-20": "three vials, clear",
    "slot7-sweep-2026-09-09-pos6-dx-10": "three vials, clear",
    "slot7-sweep-2026-09-09-pos7-dxp0": "three vials, clear",
    "slot7-sweep-2026-09-09-pos8-dxp10": "three vials, clear",
    "slot7-sweep-2026-09-09-pos9-dxp20": "three vials, clear",
    "slot7-z129-press90-2026-09-09-pos1-dx-30": "hand reaching in at the right of the deck",
    "slot7-z129-press90-2026-09-09-pos2-dxp0": "hand immediately beside the vials",
    "slot7-z129-press90-2026-09-09-pos3-dxp30": "three vials, clear",
}


def main(sha="main", width=300):
    frames = {f["name"][:-4]: f for f in json.load(open(
        os.path.join(HERE, "frames", "frames.json")))["frames"]}
    spectra = {s["file"][:-4]: s for s in json.load(open(
        os.path.join(HERE, "spectra", "spectra.json")))}

    out = ["# Every colour measurement, as a picture, a spectrum and a link", "",
           "Generated by `build_gallery.py`. Each row is one scan position: the frame",
           "the livestream was showing at the instant the sensor answered, the spectrum",
           "of that reading in the light-mixing house style, and the link back into the",
           "stream. The clock burned into each frame is the lab's local time (UTC-6) and",
           "is what the video offset was verified against.", ""]

    for run_file, title, when in RUN_TITLES:
        keys = [k for k, s in spectra.items() if s["run_file"] == run_file]
        keys.sort(key=lambda k: spectra[k]["t_first_utc"])
        if not keys:
            continue
        out += [f"## {title}", "", f"`{run_file}` · {when}", "",
                "| position | deck at that instant | spectrum | reading |",
                "| --- | --- | --- | --- |"]
        for k in keys:
            sp, fr = spectra[k], frames.get(k, {})
            frame_md = ""
            if fr:
                frame_md = (f'<img width="{width}" src="'
                            + RAW.format(sha=sha, path=f"frames/{k}.jpg") + '" />')
            plot_md = (f'<img width="{width}" src="'
                       + RAW.format(sha=sha, path=f"spectra/{k}.png") + '" />')
            note = SCENE.get(k, "")
            link = fr.get("url", "")
            cell = (f"**x = {sp['x']:.2f} mm**<br>mean total **{sp['mean_total']:.0f}**"
                    f"<br>{sp['t_first_utc'][11:19]} UTC"
                    + (f"<br>[open the stream here]({link})" if link else "")
                    + (f"<br>_{note}_" if note else "")
                    + (f"<br>overlay `{fr['overlay_local']}`" if fr else ""))
            out.append(f"| {sp['stage']} | {frame_md} | {plot_md} | {cell} |")
        out.append("")

    path = os.path.join(HERE, "measurement-gallery.md")
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    print(f"{len(spectra)} rows -> {os.path.basename(path)}")


if __name__ == "__main__":
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else "main")
