import os, json
from uuid import UUID
from edison_client import EdisonClient, TaskRequest, JobNames
from edison_client.models.app import RuntimeConfig

key = os.environ.get('EDISON_API_KEY') or os.environ.get('EDISON_PLATFORM_API_KEY')
if not key:
    raise SystemExit('Set EDISON_API_KEY (or EDISON_PLATFORM_API_KEY) in the environment.')
key = key.strip()
client = EdisonClient(api_key=key)

# Continue from the powder-disposal SOP trajectory (§12) so Edison has the full prior context.
PRIOR = "56c08a19-eebc-477b-a627-bf82808189ec"

query = r"""
Context: We operate a Nilfisk CFM 118EXP explosion-proof industrial vacuum in a university research lab
(BYU) to collect excess gas-atomized AlSi10Mg (aluminum-silicon-magnesium, ~20-63 um with sub-micron
fines) and elemental silicon powder generated by ultrasonic-atomization / additive-manufacturing
research. The vacuum has an antistatic main filter, upstream + downstream HEPA filters, a fully
conductive steel-wire-reinforced antistatic hose (end-to-end ~4 ohm, manufacturer-confirmed normal,
spec R <= 10^4 ohm), conductive aluminum wand + coupler, and a carbon-loaded conductive polyethylene
bin liner (surface resistivity ~10^3-10^5 ohm/sq) that grounds by contact against the bare steel bin
(the unit has NO separate liner bonding clip, confirmed by the manufacturer). The whole grounding chain
is multimeter-verified to building earth. Waste path: sealed conductive liner -> grounded steel interim
pail (lid set on, NOT crimped) -> BYU EHS unwanted-materials pickup. Prior Edison trajectories already
covered bag-vs-liner selection, emptying cadence, and the disposal SOP.

We are about to do the FIRST live test run: vacuuming a few grams of AlSi10Mg off a grounded metal
tray/benchtop using the CREVICE NOZZLE and DUST BRUSH, then cleaning and storing the tools. We have
written an operating procedure (companion to the disposal SOP) and need you to VERIFY it against the
combustible-metal-dust and static-control literature. For EACH numbered claim below, state whether it is
CORRECT / CORRECT-WITH-CAVEAT / INCORRECT / UNSUPPORTED, give the conservative best-practice position,
and cite specific standards (NFPA 484, 652, 654, 77; OSHA 1910; IEC/ANSI-ESD; Aluminum Association;
peer-reviewed dust-ignition/MIE literature). If a claim is unsafe or missing a critical control, say so
explicitly.

CLAIMS TO VERIFY:

1. CONTINUITY BEFORE EACH USE. Requiring a ground-continuity check before every use is appropriate, and
   these acceptance targets are defensible: conductive hose end-to-end ~4 ohm (mfr-normal), wand/coupler
   < 0.1 ohm, bin/body-to-building-ground < 1 ohm, conductive liner-in-contact-with-bin < 1 kohm to
   ground. Are these thresholds consistent with NFPA 77 / NFPA 484 bonding-and-grounding guidance
   (e.g., the < 1 Mohm / < 10 ohm criteria)? Is < 1 kohm an adequate acceptance limit for the liner?

2. NO BONDING CLIP / LINER GROUNDS BY CONTACT. For a conductive (carbon-loaded, <=10^6 ohm/sq) PE liner
   pressed against a grounded bare-metal bin, is direct-contact grounding (verified < 1 kohm) an
   acceptable substitute for a dedicated bonding clip/tab when collecting combustible aluminum fines?

3. PPE. N95 (filtering facepiece) respirator + nitrile gloves + a cotton or antistatic lab coat is
   adequate PPE for vacuuming tens of grams of AlSi10Mg; an 80/20 polyester-cotton coat should be
   avoided because it accumulates static. Is an N95 sufficient or is a higher level of respiratory /
   FR clothing warranted? Is personal grounding (wrist strap / heel strap) needed for the operator
   during vacuuming and during liner sealing?

4. TECHNIQUE. Keep powder out of the air via slow passes, nozzle kept close to the surface,
   "brush-and-capture" with the dust brush (bristles kiss the surface while airflow captures at the
   ferrule) rather than sweeping; vacuum ON before approaching powder and lift the tool away BEFORE
   switching OFF; never blow powder toward the nozzle; never use compressed air. Is this consistent with
   dust-cloud minimum-ignition-energy considerations (sub-micron Al fines MIE can be < 5 mJ)?

5. DUST-BRUSH ISOLATED-CONDUCTOR RISK. Brush bristles/ferrule are a classic isolated-conductor gap; the
   brush must be the conductive-bristle EXP variant and its ferrule-to-wand-to-inlet path must be included
   in the continuity check. Correct?

6. SEALING. Gooseneck-twist the liner 2-3 turns and secure with conductive/ESD tape or two steel zip
   ties; set the interim-pail lid on but DO NOT crimp it (crimping/sealing a lid on combustible-metal
   waste can raise the explosion/pressure hazard). Is the un-crimped-lid guidance sound, and is ESD tape
   an acceptable substitute for conductive cable ties?

7. NO PASSIVATION. Do NOT passivate the collected dry AlSi10Mg with mineral oil or water for our
   tens-of-grams scale; rely on dry, sealed, grounded containment. (Re-confirm the prior conclusion in
   light of first-run quantities.)

8. FILL / SETTLING LIMITS. Power off and wait >= 60 s for airborne dust to settle before opening; keep
   bin fill below ~25%; keep interim pail below ~50%. Are the settling time and fill limits defensible?

9. POST-USE CLEANING CADENCE. For repeated use on the SAME aluminum family (AlSi10Mg <-> Si <-> other Al),
   a full IPA cleaning is not required every session; a dry/light-IPA wipe of tool exteriors + bores plus
   running the vacuum ~15-30 s to clear the bores is adequate. A FULL IPA clean + replacing the main and
   both HEPA filters + a fresh dedicated pail is required only when switching to an INCOMPATIBLE family
   (iron/copper/nickel/Ti, thermite-precursor oxides). Is this decision rule sound?

10. CLEANING METHOD. Clean with a lint-free cloth LIGHTLY dampened with isopropyl alcohol (70% or 99%);
    NEVER water, acetone, or chlorinated solvents; NEVER wash or blow out filters; fine non-metallic
    Scotch-Brite only on metal contact faces if oxide interferes with continuity; re-verify continuity
    after any cleaning. Is IPA the right solvent choice, and is the no-water rule correctly justified
    (Al + H2O -> H2)? Any flammability caveat for using IPA near combustible metal dust?

11. TOOL STORAGE. Residual powder inside a wand/crevice/brush is itself an accumulation of combustible
    metal dust, so: clean before storing, store dry, cap/plug or bag each tool in a small conductive
    black-PE bag (not pink/silver), dedicate the set to the Al family and label it, segregate from
    oxidizers/metal-oxide powders and ignition sources, store at/near the grounded vacuum station. Is
    this storage guidance complete and correct, or is anything missing (e.g., housekeeping of the storage
    area per NFPA 654 layer-depth limits)?

12. FIRE PROTECTION. A Class D extinguisher (Met-L-X / Lith-X / NaCl-based) must be present and within
    reach; water / CO2 / ABC dry-chemical units are NOT acceptable for a metal fire. Correct placement /
    travel-distance expectations per OSHA 1910.157 / NFPA 484?

Finally: list anything IMPORTANT that our procedure OMITS for a safe first live run (e.g., a job hazard
analysis / DHA step, spill response, bonding of the tray to the vacuum ground, restricting bystanders,
handling a stuck/overheating condition), and give citations. Where the literature is genuinely silent or
quantity-dependent, say so and give the conservative recommendation.
"""

task = TaskRequest(
    name=JobNames.LITERATURE_HIGH,
    query=query,
    runtime_config=RuntimeConfig(continued_job_id=UUID(PRIOR)),
)
task_id = client.create_task(task)
print("TASK_ID", task_id)
os.makedirs(os.path.dirname(__file__) or ".", exist_ok=True)
with open(os.path.join(os.path.dirname(__file__) or ".", "_task_id.json"), "w") as f:
    json.dump({"task_id": str(task_id), "continued_from": PRIOR}, f, indent=2)
print("wrote _task_id.json")
