#!/usr/bin/env python3
"""Path B1: put the lid mount into Onshape over the REST API.

Creates a new Onshape document, then

  1. builds the base natively, as ordinary sketch and extrude features that
     stay editable in Onshape (plate, collar, posts, lens aperture, bolt holes),
  2. imports every STEP file from ../exports (base, deck, drill template,
     spacers, and the full assembly with the camera, lens and Pi 5), and
  3. optionally shares the document with collaborators.

The native features are rebuilt from lid_mount.Params, the same numbers the
CadQuery model uses, so the two paths can be compared part for part.

Credentials come from the environment, never the command line:

    ONSHAPE_ACCESS_KEY, ONSHAPE_SECRET_KEY   API keys (My Account > Developer > API keys) with
                                             the Read and Write scopes, plus Share for --share
    ONSHAPE_BASE_URL                         optional, default https://cad.onshape.com

    python onshape_api.py                          # create the document and build everything
    python onshape_api.py --share someone@byu.edu  # ...and share it (edit rights)
    python onshape_api.py --skip-native            # STEP import only
    python onshape_api.py --public                 # Free plans can only create public documents
    python onshape_api.py --document URL --skip-native --step deck   # add one STEP to an existing document

A run costs about 40 API calls. Free, Standard and EDU Student plans get 2,500 a
year (https://onshape-public.github.io/docs/auth/limits/), so polling is kept slow.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import requests

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "cad"))
from lid_mount import EXPORTS, Params, corners  # noqa: E402

API = "/api/v10"           # any explicit version works; v17 is current as of 2026-09
TOP_PLANE = "JDC"          # deterministic id of the Top plane in every new Part Studio
M = 0.001                  # sketch geometry is in metres
STEPS = ("base", "deck", "drill_template", "spacers", "assembly")   # files in ../exports, .step


class Onshape:
    def __init__(self, base_url: str, access: str, secret: str):
        self.base = base_url.rstrip("/")
        self.s = requests.Session()
        self.s.auth = (access, secret)              # Onshape accepts API keys as HTTP Basic auth
        self.s.headers["Accept"] = "application/json;charset=UTF-8; qs=0.09"

    def call(self, method: str, path: str, **kw) -> dict:
        r = self.s.request(method, self.base + API + path, timeout=120, **kw)
        if not r.ok:
            raise RuntimeError(f"{method} {path} -> HTTP {r.status_code}: {r.text[:800]}")
        return r.json() if r.content else {}

    # --- documents -----------------------------------------------------------------
    def whoami(self) -> dict:
        return self.call("GET", "/users/sessioninfo")

    def create_document(self, name: str, public: bool) -> tuple[str, str]:
        try:
            doc = self.call("POST", "/documents", json={"name": name, "isPublic": public})
        except RuntimeError as exc:
            if "409" in str(exc) and not public:
                raise RuntimeError(f"{exc}\n(Free plans can only create public documents: try --public)")
            raise
        return doc["id"], doc["defaultWorkspace"]["id"]

    def elements(self, did: str, wid: str) -> list[dict]:
        return self.call("GET", f"/documents/d/{did}/w/{wid}/elements")

    def create_part_studio(self, did: str, wid: str, name: str) -> str:
        return self.call("POST", f"/partstudios/d/{did}/w/{wid}", json={"name": name})["id"]

    def share(self, did: str, wid: str, email: str) -> None:
        self.call("POST", f"/documents/{did}/share", json={
            "documentId": did, "workspaceId": wid,
            "entries": [{"email": email, "entryType": 0}],
            "permissionSet": ["READ", "WRITE", "COPY", "EXPORT", "COMMENT", "LINK"],
            "message": "OT-2 lid camera mount (generated by onshape_api.py)",
        })

    # --- features ------------------------------------------------------------------
    def add_feature(self, did: str, wid: str, eid: str, feature: dict) -> str:
        body = {"btType": "BTFeatureDefinitionCall-1406", "feature": feature}
        out = self.call("POST", f"/partstudios/d/{did}/w/{wid}/e/{eid}/features", json=body)
        state = out.get("featureState", {}).get("featureStatus", "?")
        fid = out["feature"]["featureId"]
        print(f"  + {feature['name']:<24} {state}")
        if state not in ("OK", "INFO"):
            raise RuntimeError(f"feature {feature['name']} regenerated with status {state}")
        return fid

    # --- import --------------------------------------------------------------------
    def import_step(self, did: str, wid: str, path: Path) -> list[str]:
        before = {e["id"] for e in self.elements(did, wid)}
        with path.open("rb") as fh:
            tr = self.call("POST", f"/translations/d/{did}/w/{wid}", files={
                "file": (path.name, fh, "application/octet-stream"),
            }, data={
                # Exactly the fields of Onshape's documented example. An empty formatName
                # means "import to Onshape". Adding storeInDocument and yAxisIsUp got
                # HTTP 400 "illegal argument" from the live API (2026-09-25).
                "formatName": "", "flattenAssemblies": "true", "translate": "true",
            })
        tid = tr["id"]
        for _ in range(60):                      # every poll counts against the yearly limit
            time.sleep(10)
            st = self.call("GET", f"/translations/{tid}")
            if st["requestState"] == "DONE":
                # resultElementIds is sometimes null even on success; diff the tabs instead.
                return st.get("resultElementIds") or sorted(
                    {e["id"] for e in self.elements(did, wid)} - before)
            if st["requestState"] == "FAILED":
                raise RuntimeError(f"import of {path.name} failed: {st.get('failureReason')}")
        raise TimeoutError(f"import of {path.name} still running after 10 minutes")


class DryRun(Onshape):
    """Stands in for the API: records every request and answers with placeholders,
    so the whole flow can be exercised and its payloads reviewed without keys."""

    def __init__(self):
        self.base = "https://cad.onshape.com"
        self.log: list[dict] = []
        self.n = 0

    def call(self, method: str, path: str, **kw) -> dict:
        self.n += 1
        body = kw.get("json")
        if body is None and "data" in kw:
            body = {"form": kw["data"], "file": kw["files"]["file"][0]}
        self.log.append({"method": method, "path": API + path, "body": body})
        if path == "/users/sessioninfo":
            return {"name": "dry run"}
        if path == "/documents":
            return {"id": "DID", "defaultWorkspace": {"id": "WID"}}
        if path.endswith("/features"):
            return {"feature": {"featureId": f"F{self.n}"}, "featureState": {"featureStatus": "OK"}}
        if path.startswith("/partstudios/"):
            return {"id": "EID"}
        if path.startswith("/translations/d/"):
            return {"id": f"TID{self.n}"}
        if path.startswith("/translations/"):
            return {"requestState": "DONE", "resultElementIds": [f"E{self.n}"]}
        if path.endswith("/elements"):
            return []
        return {}


# --- feature JSON ---------------------------------------------------------------------

def quantity(pid: str, expr: str) -> dict:
    return {"btType": "BTMParameterQuantity-147", "parameterId": pid, "expression": expr, "isInteger": False}


def enum(pid: str, enum_name: str, value: str) -> dict:
    return {"btType": "BTMParameterEnum-145", "parameterId": pid, "enumName": enum_name, "value": value}


def line(eid: str, x0: float, y0: float, x1: float, y1: float) -> dict:
    dx, dy = x1 - x0, y1 - y0
    length = (dx * dx + dy * dy) ** 0.5
    return {
        "btType": "BTMSketchCurveSegment-155", "entityId": eid,
        "startPointId": f"{eid}.start", "endPointId": f"{eid}.end",
        "startParam": 0.0, "endParam": length * M,
        "geometry": {"btType": "BTCurveGeometryLine-117", "pntX": x0 * M, "pntY": y0 * M,
                     "dirX": dx / length, "dirY": dy / length},
    }


def circle(eid: str, x: float, y: float, d: float) -> dict:
    return {
        "btType": "BTMSketchCurve-4", "entityId": eid, "centerId": f"{eid}.center",
        "geometry": {"btType": "BTCurveGeometryCircle-115", "radius": d / 2 * M,
                     "xCenter": x * M, "yCenter": y * M, "xDir": 1.0, "yDir": 0.0, "clockwise": False},
    }


def rect(prefix: str, cx: float, cy: float, w: float, h: float) -> list[dict]:
    x0, x1, y0, y1 = cx - w / 2, cx + w / 2, cy - h / 2, cy + h / 2
    return [line(f"{prefix}b", x0, y0, x1, y0), line(f"{prefix}r", x1, y0, x1, y1),
            line(f"{prefix}t", x1, y1, x0, y1), line(f"{prefix}l", x0, y1, x0, y0)]


def sketch(name: str, entities: list[dict]) -> dict:
    return {
        "btType": "BTMSketch-151", "featureType": "newSketch", "name": name,
        "parameters": [{"btType": "BTMParameterQueryList-148", "parameterId": "sketchPlane",
                        "queries": [{"btType": "BTMIndividualQuery-138", "deterministicIds": [TOP_PLANE]}]}],
        "entities": entities, "constraints": [],
    }


def extrude(name: str, sketch_id: str, op: str, depth_expr: str | None) -> dict:
    params = [
        enum("bodyType", "ExtendedToolBodyType", "SOLID"),
        enum("operationType", "NewBodyOperationType", op),
        {"btType": "BTMParameterQueryList-148", "parameterId": "entities",
         "queries": [{"btType": "BTMIndividualSketchRegionQuery-140", "featureId": sketch_id}]},
    ]
    if depth_expr is None:
        params.append(enum("endBound", "BoundingType", "THROUGH_ALL"))
    else:
        params += [enum("endBound", "BoundingType", "BLIND"), quantity("depth", depth_expr)]
    if op != "NEW":
        params.append({"btType": "BTMParameterBoolean-144", "parameterId": "defaultScope", "value": True})
    return {"btType": "BTMFeature-134", "featureType": "extrude", "name": name, "parameters": params}


def build_base_natively(api: Onshape, did: str, wid: str, eid: str, p: Params) -> None:
    """The base as editable features. Nut traps, tabs and fillets are left to
    the imported STEP; everything that sets the geometry on the lid is here."""
    mm = lambda v: f"{v:g} mm"  # noqa: E731
    s1 = api.add_feature(did, wid, eid, sketch("Plate sketch", rect("p", 0, 0, p.base_size, p.base_size)))
    api.add_feature(did, wid, eid, extrude("Plate", s1, "NEW", mm(p.base_t)))
    s2 = api.add_feature(did, wid, eid, sketch("Collar sketch", [circle("c", 0, 0, p.aperture_d + 2 * p.collar_wall)]))
    api.add_feature(did, wid, eid, extrude("Collar", s2, "ADD", mm(p.base_t + p.collar_h)))
    posts = [e for i, (x, y) in enumerate(corners(p.post_c)) for e in rect(f"q{i}", x, y, p.post_w, p.post_w)]
    s3 = api.add_feature(did, wid, eid, sketch("Posts sketch", posts))
    api.add_feature(did, wid, eid, extrude("Posts", s3, "ADD", mm(round(p.z_deck, 2))))
    holes = [circle("ap", 0, 0, p.aperture_d)]
    holes += [circle(f"b{i}", x, y, p.bolt_clear_d) for i, (x, y) in enumerate(corners(p.bolt_xy))]
    s4 = api.add_feature(did, wid, eid, sketch("Holes sketch", holes))
    api.add_feature(did, wid, eid, extrude("Aperture and bolt holes", s4, "REMOVE", None))


def git_sha() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short=7", "HEAD"], capture_output=True, text=True,
                              cwd=HERE, check=True).stdout.strip()
    except Exception:
        return "local"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", default=f"OT-2 lid camera mount ({git_sha()})")
    ap.add_argument("--share", action="append", default=[], metavar="EMAIL")
    ap.add_argument("--skip-native", action="store_true", help="only import the STEP files")
    ap.add_argument("--skip-import", action="store_true", help="only build the native base")
    ap.add_argument("--public", action="store_true", help="create a public document (needed on Free plans)")
    ap.add_argument("--document", metavar="URL", help="work in an existing document instead of creating one")
    ap.add_argument("--step", action="append", choices=STEPS, metavar="NAME",
                    help=f"import only this STEP file (repeatable; default all of: {', '.join(STEPS)})")
    ap.add_argument("--dry-run", action="store_true",
                    help="no network: run the whole flow against a stub and save every request to dry_run.json")
    args = ap.parse_args()

    if args.dry_run:
        api = DryRun()
        time.sleep = lambda _s: None             # noqa: E731  (no waiting on a stub)
    else:
        access, secret = os.environ.get("ONSHAPE_ACCESS_KEY"), os.environ.get("ONSHAPE_SECRET_KEY")
        if not (access and secret):
            raise SystemExit("ONSHAPE_ACCESS_KEY and ONSHAPE_SECRET_KEY must be set (see the README).")
        api = Onshape(os.environ.get("ONSHAPE_BASE_URL", "https://cad.onshape.com"), access, secret)
    print("signed in as", api.whoami().get("name", "?"))

    if args.document:
        m = re.search(r"/documents/(\w+)/w/(\w+)", args.document)
        if not m:
            raise SystemExit(f"not a workspace URL: {args.document}")
        did, wid = m.groups()
    else:
        did, wid = api.create_document(args.name, args.public)
    url = f"{api.base}/documents/{did}/w/{wid}"
    print("document:", url)
    failures = []
    if not args.skip_native:
        eid = api.create_part_studio(did, wid, "Base (native features)")
        print("building the base natively in 'Base (native features)'")
        try:
            build_base_natively(api, did, wid, eid, Params())
        except Exception as exc:          # keep going: the STEP import still gives a full model
            failures.append(f"native build: {exc}")
            print("  !", exc)
    if not args.skip_import:
        for name in args.step or STEPS:
            path = EXPORTS / f"{name}.step"
            try:
                ids = api.import_step(did, wid, path)
                print(f"imported {path.name} -> elements {ids}")
            except Exception as exc:
                failures.append(f"import {path.name}: {exc}")
                print("  !", exc)
    for email in args.share:
        api.share(did, wid, email)
        print("shared with", email)
    summary = {"document": url, "failures": failures}
    if args.dry_run:
        summary["api_calls"] = api.n
        (HERE / "dry_run.json").write_text(json.dumps(api.log, indent=1) + "\n")
    else:
        (HERE / "last_run.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))
    if failures:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
